In [1]:
import pandas as pd
import re
import random

In [2]:
d = pd.read_csv('./clothes2.csv',header= 0)
df = pd.read_csv('./clothes.csv')
# 合并
df = pd.concat([d, df], ignore_index=True)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18663 entries, 0 to 18662
Data columns (total 18 columns):
关键词      18663 non-null object
页码       18663 non-null int64
商品ID     17725 non-null float64
标题       17725 non-null object
价格       17725 non-null float64
原价描述     12571 non-null object
店铺名称     17725 non-null object
实际销量     18662 non-null object
发货地      17725 non-null object
是否广告     18663 non-null bool
店铺URL    17725 non-null object
商品链接     17725 non-null object
优惠标签     17661 non-null object
属性       18663 non-null object
商品封面     17725 non-null object
热门标签     1405 non-null object
商品卖点     2660 non-null object
店铺标签     13005 non-null object
dtypes: bool(1), float64(2), int64(1), object(14)
memory usage: 2.4+ MB

In [60]:
df.head(100)

,关键词,页码,商品ID,标题,价格,原价描述,店铺名称,实际销量,发货地,是否广告,店铺URL,商品链接,优惠标签,属性,商品封面,热门标签,商品卖点,店铺标签
0,阿迪达斯,1,7.934758e+11,「小锯齿」D-PAD CLASSIC美高风篮球风板鞋男女adidas阿迪达斯,329.00,券后价,adidas官方旗舰店,2万+人付款,江苏 苏州,True,http://click.simba.taobao.com/cc_im?p=%B0%A2%B...,http://click.simba.taobao.com/cc_im?p=%B0%A2%B...,包邮,"['鞋底材质:橡胶', '鞋帮高度:低帮', '适用人群:通用', '品牌:adidas',...",http://g.search2.alicdn.com/img/i2/2987720082/...,NaN,['69万+穿搭控看过'],回头客20万
1,阿迪达斯,1,9.932150e+11,Adidas阿迪达斯三叶草新款秋冬潮流新中式唐装复古外套男女KR0295,655.35,券后价,马铃薯体育,1万+人看过,四川 成都,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://item.taobao.com/item.htm?id=9932150046...,热销爆款|全球购|酷动城,[],https://g-search2.alicdn.com/img/bao/uploaded/...,NaN,NaN,NaN
2,阿迪达斯,1,9.892873e+11,阿迪达斯礼品卡1000元 Adidas电子卡 代金券 卡密 购物卡,940.00,券后价,天天好券,1人付款,北京,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://item.taobao.com/item.htm?id=9892873271...,包邮,[],https://g-search2.alicdn.com/img/bao/uploaded/...,NaN,NaN,回头客2万
3,阿迪达斯,1,8.548670e+11,ADIZERO ADIOS PRO 4专业竞速碳柱跑鞋男女adidas阿迪达斯官方,1699.00,券后价,adidas官方旗舰店,900+人付款,江苏 苏州,True,http://click.simba.taobao.com/cc_im?p=%B0%A2%B...,http://click.simba.taobao.com/cc_im?p=%B0%A2%B...,包邮,"['适用场景:专业马拉松', '中底科技:LightStrike Pro', '适用性别:男...",http://g.search2.alicdn.com/img/i2/2987720082/...,NaN,['9万+穿搭控看过'],回头客20万
4,阿迪达斯,1,8.641054e+11,「T头鞋」BARREDA休闲板鞋德训鞋男女adidas阿迪达斯官方轻运动,349.00,券后价,adidas官方旗舰店,10万+人付款,广东 江门,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=864105409...,次日达|包邮,[],https://g-search2.alicdn.com/img/bao/uploaded/...,{'rank_short_text': '板鞋好评榜·第2名'},NaN,回头客20万
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,阿迪达斯,2,6.834618e+11,EQ19 RUN随心畅跑舒适跑步运动鞋男女adidas阿迪达斯官方,239.00,券后价,adidas官方旗舰店,8000+人付款,广东 江门,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=683461816...,次日达|包邮,"['适用场景:休闲健步', '中底科技:CLOUDFOAM', '鞋底材质:橡胶', '适用...",https://g-search1.alicdn.com/img/bao/uploaded/...,NaN,NaN,回头客20万
107,阿迪达斯,2,7.884527e+11,FOS系列轻机甲鞋-赛博 XLG RUNNER DELUXE厚底跑鞋adidas阿迪达斯,1299.00,券后价,adidas官方旗舰店,1000+人付款,江苏 苏州,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=788452683...,48小时内发|包邮,"['适用对象:男女通用', '鞋帮高度:低帮', '闭合方式:系带', '运动系列:休闲',...",https://g-search3.alicdn.com/img/bao/uploaded/...,NaN,NaN,回头客20万
108,阿迪达斯,2,9.712557e+11,拒水长款休闲保暖鸭绒羽绒服男女秋冬新款adidas阿迪达斯轻运动,829.00,券后价,adidas官方旗舰店,1000+人付款,江苏 苏州,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=971255653...,次日达|包邮,"['填充物:鸭绒', '衣长:长款', '是否商场同款:商场同款', '适用对象:男女通用'...",https://g-search3.alicdn.com/img/bao/uploaded/...,NaN,NaN,回头客20万
109,阿迪达斯,2,8.653899e+11,ADIZERO ADIOS 9全速争胜马拉松薄底竞速跑鞋男女adidas阿迪达斯,799.00,券后价,adidas官方旗舰店,800+人付款,江苏 苏州,False,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=865389864...,次日达|包邮,"['适用场景:竞速', '中底科技:LightStrike Pro', '适用性别:男女通用...",https://g-search1.alicdn.com/img/bao/uploaded/...,NaN,NaN,回头客20万
110,阿迪达斯,3,9.414858e+11,SPEZIAL系列 T头鞋 HANDBALL运动鞋德训鞋adidas阿迪达斯三叶草,539.00,券后价,adidas官方旗舰店,400+人付款,江苏 苏州,True,http://click.simba.taobao.com/cc_im?p=%B0%A2%B...,http://click.simba.taobao.com/cc_im?p=%B0%A2%B...,包邮,"['鞋帮高度:低帮', '适用人群:通用', '品牌:adidas', '鞋码:48.5']",http://g.search.alicdn.com/img/i4/2987720082/O...,NaN,['2万+穿搭控看过'],回头客20万

In [56]:
# 根据商品id去重
df.drop_duplicates(subset=['商品ID'], inplace=True)

In [58]:
# 删除价格字段为空和不是数字的行
df.dropna(subset=['价格'], inplace=True)

In [59]:
# 把原价描述字段为NAN填充为券后价
df['原价描述'] = df['原价描述'].fillna("券后价")

In [61]:
def parse_sale_volume(x):
    if pd.isna(x):
        return None
    x = str(x)
    x = x.replace("人付款", "").replace("人看过", "").strip()
    if "万+" in x:
        num = x.replace("万+", "")
        base = int(float(num) * 10000)
        return random.randint(base, base + 3000)
    if "+" in x:
        base = int(re.findall(r"\d+", x)[0])
        return random.randint(base, base + int(base * 0.2))
    return int(re.findall(r"\d+", x)[0])

df["实际销量"] = df["实际销量"].apply(parse_sale_volume)

In [62]:
df["是否广告"] = df["是否广告"].astype(int)

In [63]:
# 处理地区
def split_location(x):
    if pd.isna(x):
        return pd.Series([None, None])
    x = str(x).strip()
    parts = x.split()
    if len(parts) == 1:
        return pd.Series([parts[0], parts[0]])
    else:
        return pd.Series([parts[0], parts[1]])

df[["province", "city"]] = df["发货地"].apply(split_location)

In [64]:
# 清洗出版型和面料
def extract_style_material(x):
    # 默认值
    style = "未知"
    material = "未知"

    if pd.isna(x):
        return pd.Series([style, material])

    x = str(x)

    # 匹配 版型
    style_match = re.search(r"版型:([^,'\]]+)", x)
    if style_match:
        style = style_match.group(1)

    # 匹配 面料
    material_match = re.search(r"面料:([^,'\]]+)", x)
    if material_match:
        material = material_match.group(1)

    return pd.Series([style, material])
df[["版型", "面料"]] = df["属性"].apply(extract_style_material)

In [65]:
# 转换热门标签变成列表
import ast
def clean_hot_tags(x):
    if pd.isna(x):
        return []
    if isinstance(x, dict):
        if "rank_short_text" in x and x["rank_short_text"]:
            return [x["rank_short_text"]]
        else:
            return []
    if isinstance(x, str):
        x = x.strip()

        if x == "" or x == "{}":
            return []

        try:
            d = ast.literal_eval(x)  # 安全转 dict
            if isinstance(d, dict) and "rank_short_text" in d and d["rank_short_text"]:
                return [d["rank_short_text"]]
            else:
                return []
        except:
            return []
    return []
df["热门标签"] = df["热门标签"].apply(clean_hot_tags)

In [67]:
# 删除字段
df.drop(columns=["关键词", "页码"], inplace=True)

In [68]:
import numpy as np
n = len(df)
# 添加随机时间字段格式为2025-12-05 17:28:35 时间区段2025-01-01 00:00:00 - 2025-12-5 23:59:59
# 时间范围
start = pd.Timestamp("2025-01-01 00:00:00").timestamp()
end   = pd.Timestamp("2025-12-05 23:59:59").timestamp()
# 生成随机时间戳
random_timestamps = np.random.uniform(start, end, n)
# 转换为 datetime
df["时间"] = pd.to_datetime(random_timestamps, unit='s')

In [38]:
df.head()

,product_id,title,price,original_price_desc,shop_name,real_sales,ship_from,is_ad,shop_url,product_url,...,attributes,cover_img,hot_tag,selling_point,shop_tag,province,city,style_type,material,时间
0,7.862645e+11,alex stevens遮副乳宽肩带吊带连衣裙女春秋海边度假收腰长裙子,141.0,券后价,alex stevens (xm定制),6492,广东 深圳,1,http://click.simba.taobao.com/cc_im?p=%C1%AC%D...,http://click.simba.taobao.com/cc_im?p=%C1%AC%D...,...,"['版型:修身型', '面料:棉95%', '款式:背带', '适用人群:女士', '适用场...",http://g.search.alicdn.com/img/i4/3296879265/O...,[],['62万+穿搭控看过'],回头客10万,广东,深圳,修身型,棉95%,2025-07-29 10:02:53.011997461
1,9.941393e+11,【意向金】雾月绮梦~梨岛甜茶Lolita原创连衣裙~意向金1r抵10r,1.0,券后价,梨岛甜茶,3359,广东 广州,0,https://store.taobao.com/shop/view_shop.htm?ap...,https://item.taobao.com/item.htm?id=9941392920...,...,"['主题名称:雾月绮梦', '风格:甜美风']",https://g-search3.alicdn.com/img/bao/uploaded/...,[],,,广东,广州,未知,未知,2025-06-08 17:43:49.427591085
2,9.878618e+11,圣诞节新年巨好看的红色针织连衣裙深秋初冬季富家千金miu系裙子,68.9,券后价,欧莉碧旗舰店,113,广东 广州,0,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=987861811...,...,"['版型:裙摆型', '面料:聚酯纤维', '款式:长袖连衣裙', '适用人群:少女', '...",https://g-search3.alicdn.com/img/bao/uploaded/...,[],,回头客3万,广东,广州,裙摆型,聚酯纤维,2025-01-26 04:29:34.266060591
3,9.024360e+11,灰色针织连衣裙女秋季长款收腰气质长袖打底内搭长裙,139.0,券后价,RICH IN CHEESE 舒胡蕾,2292,浙江 杭州,1,http://click.simba.taobao.com/cc_im?p=%C1%AC%D...,http://click.simba.taobao.com/cc_im?p=%C1%AC%D...,...,"['版型:修身型', '面料:聚酯纤维', '款式:针织连衣裙', '适用人群:女士', '...",https://img.alicdn.com/imgextra/i2/22195502444...,[],['10万+韩系穿搭控看过'],回头客2万,浙江,杭州,修身型,聚酯纤维,2025-02-16 01:43:13.409573793
4,9.853047e+11,LULUPAWNS针织连衣裙女秋冬中长款半高领设计排扣内搭遮屁股毛衣,2600.0,券后价,LULUPAWNS旗舰店,11,福建 泉州,0,https://store.taobao.com/shop/view_shop.htm?ap...,https://detail.tmall.com/item.htm?id=985304695...,...,"['版型:宽松型', '面料:聚酯纤维', '款式:A字裙', '适用人群:女士', '适用...",https://gw.alicdn.com/imgextra/O1CN01uiQOeo1Jv...,[],,,福建,泉州,宽松型,聚酯纤维,2025-12-05 02:32:37.820379734

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8621 entries, 0 to 13584
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   商品ID      8621 non-null   float64
 1   标题        8621 non-null   object
 2   价格        8621 non-null   float64
 3   原价描述      8621 non-null   object
 4   店铺名称      8621 non-null   object
 5   实际销量      8620 non-null   float64
 6   发货地       8621 non-null   object
 7   是否广告      8621 non-null   int32
 8   店铺URL     8621 non-null   object
 9   商品链接      8621 non-null   object
 10  优惠标签      8610 non-null   object
 11  属性        8621 non-null   object
 12  商品封面      8621 non-null   object
 13  热门标签      8621 non-null   object
 14  商品卖点      995 non-null    object
 15  店铺标签      6894 non-null   object
 16  province  8621 non-null   object
 17  city      8621 non-null   object
 18  版型        8621 non-null   object
 19  面料        8621 non-null   object
dtypes: float64(3), int32(1), object(16)
memory usage: 1.3+ MB

In [69]:
# 存入数据库
df = df.rename(columns={
    "商品ID": "product_id",
    "标题": "title",
    "价格": "price",
    "原价描述": "original_price_desc",
    "店铺名称": "shop_name",
    "实际销量": "real_sales",
    "发货地": "ship_from",
    "是否广告": "is_ad",
    "店铺URL": "shop_url",
    "商品链接": "product_url",
    "优惠标签": "coupon_tag",
    "属性": "attributes",
    "商品封面": "cover_img",
    "热门标签": "hot_tag",
    "商品卖点": "selling_point",
    "店铺标签": "shop_tag",
    "province": "province",
    "city": "city",
    "版型": "style_type",
    "面料": "material",
    "时间": "create_time"
})
df["real_sales"] = df["real_sales"].fillna(0).astype(int)

df["is_ad"] = df["is_ad"].astype(int)
text_cols = [
    "title", "original_price_desc", "shop_name", "ship_from",
    "shop_url", "product_url", "coupon_tag", "attributes",
    "cover_img", "hot_tag", "selling_point", "shop_tag",
    "province", "city", "style_type", "material"
]
for col in text_cols:
    df[col] = df[col].fillna("").astype(str)

In [70]:
from sqlalchemy import create_engine
import pymysql
host = "localhost"
user = "root"
password = "1234"
database = "ecommerce"

engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}/{database}?charset=utf8mb4"
)

df.to_sql(
    name="product_data",
    con=engine,
    if_exists="append", 
    index=False,
    chunksize=1000
)
print("数据已成功写入表")

数据已成功写入表